# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
 - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=4

before_script:
  - composer validate
  - composer self-update || true
  - "if [ \"$PHPCS_TEST\" = \"1\" ]; then composer require --dev squizlabs/php_codesniffer; fi"
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit translatable/tests/
